export default {
   "status":"success",
   "data":{
      "mosaic_header":{
         "template":1,
         "datetime":"2015-09-03 07:25:23"
      },
      "promo_block":{
         "title":"",
         "elements":[
            {
               "type":"bp",
               "context":"strap",
               "slots":3,
               "id":30120,
               "name":"LA VUELTA AL COLE  Strap-slot 3-2",
               "image":"http:\/\/bnr.privalia.com\/images\/e062b145c0d12832abae9daa7e055025.gif",
               "title":"LA VUELTA AL COLE  Strap-slot 3-2",
               "url":"",
               "target":""
            },
            {
               "type":"s",
               "context":"",
               "slots":6,
               "id":13290,
               "name":"03\/09 SLIDE 1 Mustang",
               "image":"http:\/\/bnr.privalia.com\/images\/d7d2e0cf5fbc8127c666afa7e310e874.jpg",
               "title":"03\/09 SLIDE 1 Mustang",
               "url":"http:\/\/es.privalia.com\/microsites\/home\/campaign\/166120",
               "target":""
            }
         ]
      },
      "premium_block":{
         "title":"Hoy en Premium a partir de las 20h",
         "elements":[

         ]
      },
      "highlight_block":{
         "title":"Destacados",
         "elements":[
            {
               "type":"cp",
               "slots":3,
               "id":163080,
               "name":"Women&#039;secret",
               "image":"\/front\/get\/photo\/163080_-_images_-_960ximg-mosaic-open-slot3.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Women&#039;secret-\/id\/163080\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-08 23:59",
               "endday":"2"
            },
            {
               "type":"cp",
               "slots":3,
               "id":172310,
               "name":"Benetton kid",
               "image":"\/front\/get\/photo\/172310_-_images_-_960ximg-mosaic-open-slot3.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Benetton-kid-\/id\/172310\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-09 23:59",
               "endday":"3"
            },
            {
               "type":"cp",
               "slots":3,
               "id":166120,
               "name":"Mustang",
               "image":"\/front\/get\/photo\/166120_-_images_-_960ximg-mosaic-open-slot3.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Mustang-\/id\/166120\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-08 23:59",
               "endday":"2"
            }
         ]
      },
      "today_block":{
         "title":"Hoy estrenamos",
         "elements":[
            {
               "type":"cp",
               "slots":2,
               "id":165150,
               "name":"Volcom",
               "image":"\/front\/get\/photo\/165150_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Volcom-\/id\/165150\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-08 23:59",
               "endday":"2"
            },
            {
               "type":"cp",
               "slots":1,
               "id":163400,
               "name":"Diesel Shoes",
               "image":"\/front\/get\/photo\/163400_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Diesel-Shoes-\/id\/163400\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"bp",
               "context":"",
               "slots":1,
               "id":20500,
               "name":"1- 11 Philips Avent",
               "image":"http:\/\/bnr.privalia.com\/images\/1a56c8c1150df6fa08f8c2eeeda050ec.png",
               "title":"1- 11 Philips Avent",
               "url":"http:\/\/es.privalia.com\/microsites\/home\/campaign\/166670",
               "target":""
            },
            {
               "type":"cp",
               "slots":2,
               "id":166670,
               "name":"Philips Avent",
               "image":"\/front\/get\/photo\/166670_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Philips-Avent-\/id\/166670\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-09 23:59",
               "endday":"3"
            },
            {
               "type":"cp",
               "slots":2,
               "id":171810,
               "name":"Leone 1947",
               "image":"\/front\/get\/photo\/171810_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Leone-1947-\/id\/171810\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-09 23:59",
               "endday":"3"
            },
            {
               "type":"cp",
               "slots":1,
               "id":161670,
               "name":"La Morena",
               "image":"\/front\/get\/photo\/161670_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/La-Morena-\/id\/161670\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":164230,
               "name":"Famosa",
               "image":"\/front\/get\/photo\/164230_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Famosa-\/id\/164230\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-07 23:59",
               "endday":"1"
            },
            {
               "type":"bp",
               "context":"",
               "slots":2,
               "id":4110,
               "name":"2-6 TC: School Shoes (HASTA 04\/09)",
               "image":"http:\/\/bnr.privalia.com\/images\/e0055fa419a3d139f599068520793b9c.jpg",
               "title":"2-6 TC: School Shoes (HASTA 04\/09)",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/category\/14020#category\/14020",
               "target":""
            },
            {
               "type":"bp",
               "context":"",
               "slots":2,
               "id":4100,
               "name":"2-5 TC: Jeans (HASTA 04\/09)",
               "image":"http:\/\/bnr.privalia.com\/images\/6730bb6258f850bc180204a8862bf2a2.jpg",
               "title":"2-5 TC: Jeans (HASTA 04\/09)",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/category\/12670#category\/12670",
               "target":""
            },
            {
               "type":"cp",
               "slots":1,
               "id":160250,
               "name":"Michael Kors & Tous Sunglasses",
               "image":"\/front\/get\/photo\/160250_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Michael-Kors-&-Tous-Sunglasses-\/id\/160250\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-07 23:59",
               "endday":"1"
            },
            {
               "type":"cp",
               "slots":1,
               "id":167660,
               "name":"Dogo",
               "image":"\/front\/get\/photo\/167660_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Dogo-\/id\/167660\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":2,
               "id":172230,
               "name":"La belle fran\u00e7aise",
               "image":"\/front\/get\/photo\/172230_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/La-belle-fran\u00e7aise-\/id\/172230\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":2,
               "id":171820,
               "name":"SPECIALE CROSSFIT by HighPower",
               "image":"\/front\/get\/photo\/171820_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/SPECIALE-CROSSFIT-by-HighPower-\/id\/171820\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-08 23:59",
               "endday":"2"
            },
            {
               "type":"cp",
               "slots":1,
               "id":171760,
               "name":"TFT Arredo Bagno",
               "image":"\/front\/get\/photo\/171760_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/TFT-Arredo-Bagno-\/id\/171760\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-12 23:59",
               "endday":"6"
            },
            {
               "type":"bp",
               "context":"",
               "slots":1,
               "id":1870,
               "name":"1- 2 Premium",
               "image":"http:\/\/bnr.privalia.com\/images\/78041c665a72c315efaf9e3f26694415.gif",
               "title":"1- 2 Premium",
               "url":"http:\/\/es.privalia.com\/microsites\/premium",
               "target":""
            },
            {
               "type":"cp",
               "slots":2,
               "id":172780,
               "name":"Timberland",
               "image":"\/front\/get\/photo\/172780_-_images_-_960ximg-mosaic-preopen-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Timberland-\/id\/172780\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-03 07:00:00",
               "startday":"4",
               "enddate":"2015-09-03 17:59",
               "endday":"4"
            },
            {
               "type":"cp",
               "slots":1,
               "id":172740,
               "name":"Timberland Kid",
               "image":"\/front\/get\/photo\/172740_-_images_-_960ximg-mosaic-preopen-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Timberland-Kid-\/id\/172740\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-03 07:00:00",
               "startday":"4",
               "enddate":"2015-09-03 17:59",
               "endday":"4"
            },
            {
               "type":"cp",
               "slots":1,
               "id":162380,
               "name":"Pikolin Home",
               "image":"\/front\/get\/photo\/162380_-_images_-_960ximg-mosaic-preopen-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Pikolin-Home-\/id\/162380\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-03 07:00:00",
               "startday":"4",
               "enddate":"2015-09-03 17:59",
               "endday":"4"
            },
            {
               "type":"cp",
               "slots":1,
               "id":162370,
               "name":"Pikolin Descanso",
               "image":"\/front\/get\/photo\/162370_-_images_-_960ximg-mosaic-preopen-slot1.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Pikolin-Descanso-\/id\/162370\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-03 07:00:00",
               "startday":"4",
               "enddate":"2015-09-03 17:59",
               "endday":"4"
            }
         ]
      },
      "home_block":{
         "title":"Home&Decor",
         "elements":[
            {
               "type":"cp",
               "slots":2,
               "id":158700,
               "name":"Habitaciones infantiles",
               "image":"\/front\/get\/photo\/158700_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Habitaciones-infantiles-\/id\/158700\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-08 23:59",
               "endday":"2"
            },
            {
               "type":"cp",
               "slots":1,
               "id":159920,
               "name":"Minimal Home",
               "image":"\/front\/get\/photo\/159920_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Minimal-Home-\/id\/159920\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":163370,
               "name":"Industrial Loft",
               "image":"\/front\/get\/photo\/163370_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Industrial-Loft-\/id\/163370\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-07 23:59",
               "endday":"1"
            },
            {
               "type":"cp",
               "slots":1,
               "id":160970,
               "name":"Sit Design",
               "image":"\/front\/get\/photo\/160970_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Sit-Design-\/id\/160970\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":151300,
               "name":"Casa con estilo",
               "image":"\/front\/get\/photo\/151300_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Casa-con-estilo-\/id\/151300\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            }
         ]
      },
      "active_block":{
         "title":"Actualmente",
         "elements":[
            {
               "type":"cp",
               "slots":2,
               "id":158840,
               "name":"mini MUNICH",
               "image":"\/front\/get\/photo\/158840_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/mini-MUNICH-\/id\/158840\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-07 23:59",
               "endday":"1"
            },
            {
               "type":"bp",
               "context":"",
               "slots":1,
               "id":20490,
               "name":"1- 10  Vuelta al cole",
               "image":"http:\/\/bnr.privalia.com\/images\/642290eebc2a8ea27180cfc17cde5f6b.gif",
               "title":"1- 10  Vuelta al cole",
               "url":"http:\/\/es.privalia.com\/landing\/info2",
               "target":""
            },
            {
               "type":"cp",
               "slots":1,
               "id":162420,
               "name":"Iris",
               "image":"\/front\/get\/photo\/162420_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Iris-\/id\/162420\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-07 23:59",
               "endday":"1"
            },
            {
               "type":"cp",
               "slots":2,
               "id":164150,
               "name":"MANGO",
               "image":"\/front\/get\/photo\/164150_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/MANGO-\/id\/164150\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":2,
               "id":159150,
               "name":"Trasluz",
               "image":"\/front\/get\/photo\/159150_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Trasluz-\/id\/159150\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-07 23:59",
               "endday":"1"
            },
            {
               "type":"cp",
               "slots":1,
               "id":162320,
               "name":"Mr. Fox",
               "image":"\/front\/get\/photo\/162320_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Mr.-Fox-\/id\/162320\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":152550,
               "name":"Rosalita Mcgee & Se\u00f1oritas",
               "image":"\/front\/get\/photo\/152550_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Rosalita-Mcgee-&-Se\u00f1oritas-\/id\/152550\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":2,
               "id":159020,
               "name":"Geographical Norway",
               "image":"\/front\/get\/photo\/159020_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Geographical-Norway-\/id\/159020\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"bp",
               "context":"",
               "slots":2,
               "id":20680,
               "name":"Unicef TODAS slot 2-9",
               "image":"http:\/\/bnr.privalia.com\/images\/cef45d5077f6212e364d7e40e6826263.jpg",
               "title":"Unicef TODAS slot 2-9",
               "url":"http:\/\/es.privalia.com\/microsites\/index\/classification\/40",
               "target":""
            },
            {
               "type":"cp",
               "slots":1,
               "id":168810,
               "name":"Geographical Norway kids",
               "image":"\/front\/get\/photo\/168810_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Geographical-Norway-kids-\/id\/168810\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":162310,
               "name":"Burrito Blanco",
               "image":"\/front\/get\/photo\/162310_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Burrito-Blanco-\/id\/162310\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":2,
               "id":165170,
               "name":"Hugo Boss",
               "image":"\/front\/get\/photo\/165170_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Hugo-Boss-\/id\/165170\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-05 23:59",
               "endday":"6"
            },
            {
               "type":"cp",
               "slots":2,
               "id":158780,
               "name":"HURLEY",
               "image":"\/front\/get\/photo\/158780_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/HURLEY-\/id\/158780\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":162740,
               "name":"Especial kids \/ \u00a1Qu\u00e9 llueva, qu\u00e9 llueva!",
               "image":"\/front\/get\/photo\/162740_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Especial-kids-\/-\u00a1Qu\u00e9-llueva,-qu\u00e9-llueva!-\/id\/162740\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":166230,
               "name":"Joid&#039;art",
               "image":"\/front\/get\/photo\/166230_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Joid&#039;art-\/id\/166230\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"bp",
               "context":"",
               "slots":2,
               "id":2270,
               "name":"2-3 TC:Office Style (HASTA 03\/09)",
               "image":"http:\/\/bnr.privalia.com\/images\/086e8f3a4428ec5e3bb3d9c72ad23292.jpg",
               "title":"2-3 TC:Office Style (HASTA 03\/09)",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/category\/13970#category\/13970",
               "target":""
            },
            {
               "type":"cp",
               "slots":2,
               "id":162760,
               "name":"Chyston 76",
               "image":"\/front\/get\/photo\/162760_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Chyston-76-\/id\/162760\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-04 23:59",
               "endday":"5"
            },
            {
               "type":"cp",
               "slots":1,
               "id":160400,
               "name":"Lola Palacios",
               "image":"\/front\/get\/photo\/160400_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Lola-Palacios-\/id\/160400\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":160780,
               "name":"Bailarinas de piel by Duendy",
               "image":"\/front\/get\/photo\/160780_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Bailarinas-de-piel-by-Duendy-\/id\/160780\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-04 23:59",
               "endday":"5"
            },
            {
               "type":"bp",
               "context":"",
               "slots":2,
               "id":20660,
               "name":"2-7 TC: Perfumes (HASTA 06\/09)",
               "image":"http:\/\/bnr.privalia.com\/images\/ab8e4c05f8aa891a56b4435f5d510d98.jpg",
               "title":"2-7 TC: Perfumes (HASTA 06\/09)",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/category\/9550#category\/9550",
               "target":""
            },
            {
               "type":"cp",
               "slots":2,
               "id":171600,
               "name":"Especial Gafas - Sport Eyewear",
               "image":"\/front\/get\/photo\/171600_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Especial-Gafas---Sport-Eyewear-\/id\/171600\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":166470,
               "name":"Sonnax Shoes",
               "image":"\/front\/get\/photo\/166470_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Sonnax-Shoes-\/id\/166470\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-04 23:59",
               "endday":"5"
            },
            {
               "type":"cp",
               "slots":1,
               "id":162970,
               "name":"Homedics \/ Rio Beauty",
               "image":"\/front\/get\/photo\/162970_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Homedics-\/-Rio-Beauty-\/id\/162970\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":2,
               "id":171780,
               "name":"Drunknmunky",
               "image":"\/front\/get\/photo\/171780_-_images_-_960ximg-mosaic-open-slot2.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Drunknmunky-\/id\/171780\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-08 23:59",
               "endday":"2"
            },
            {
               "type":"cp",
               "slots":1,
               "id":166340,
               "name":"Excelsa",
               "image":"\/front\/get\/photo\/166340_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Excelsa-\/id\/166340\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-05 23:59",
               "endday":"6"
            },
            {
               "type":"cp",
               "slots":1,
               "id":171710,
               "name":"Gift company Italy",
               "image":"\/front\/get\/photo\/171710_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Gift-company-Italy-\/id\/171710\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":171630,
               "name":"Biciclette F.lli Masciaghi",
               "image":"\/front\/get\/photo\/171630_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Biciclette-F.lli-Masciaghi-\/id\/171630\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-07 23:59",
               "endday":"1"
            },
            {
               "type":"cp",
               "slots":1,
               "id":163040,
               "name":"Purline - Climacity",
               "image":"\/front\/get\/photo\/163040_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Purline---Climacity-\/id\/163040\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":160160,
               "name":"H.Koenig",
               "image":"\/front\/get\/photo\/160160_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/H.Koenig-\/id\/160160\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            },
            {
               "type":"cp",
               "slots":1,
               "id":159960,
               "name":"Modernist Creation by Oliver Lapidus",
               "image":"\/front\/get\/photo\/159960_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Modernist-Creation-by-Oliver-Lapidus-\/id\/159960\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-06 23:59",
               "endday":"7"
            }
         ]
      },
      "home1_block":{
         "title":"Muebles y decoraci\u00f3n",
         "elements":[

         ]
      },
      "home2_block":{
         "title":"Comer y cocinar",
         "elements":[

         ]
      },
      "home3_block":{
         "title":"Electrodom\u00e9sticos y electr\u00f3nica",
         "elements":[

         ]
      },
      "home4_block":{
         "title":"Dormitorio",
         "elements":[

         ]
      },
      "home5_block":{
         "title":"Jard\u00edn y exteriores",
         "elements":[

         ]
      },
      "home6_block":{
         "title":"Sillas y sof\u00e1s",
         "elements":[

         ]
      },
      "home7_block":{
         "title":"Ba\u00f1o",
         "elements":[

         ]
      },
      "home8_block":{
         "title":"Ocio",
         "elements":[

         ]
      },
      "home9_block":{
         "title":"",
         "elements":[
            {
               "type":"bp",
               "context":"top1",
               "slots":3,
               "id":12330,
               "name":"TOP BANNER promo-top1-1   TODAS",
               "image":"http:\/\/bnr.privalia.com\/images\/81f43880f3047d88a2af3477feacfa4a.jpg",
               "title":"TOP BANNER promo-top1-1   TODAS",
               "url":"",
               "target":"_blank"
            },
            {
               "type":"bp",
               "context":"",
               "slots":1,
               "id":20530,
               "name":"SLOT 1-14 TODAS",
               "image":"http:\/\/bnr.privalia.com\/images\/45dcccf348c0cd773d1121dd0a7de7a5.jpg",
               "title":"SLOT 1-14 TODAS",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/category\/2360#category\/2360",
               "target":""
            },
            {
               "type":"bp",
               "context":"",
               "slots":1,
               "id":20520,
               "name":"SLOT 1-13 MP GENERICO",
               "image":"http:\/\/bnr.privalia.com\/images\/346286485372ffa587b49e116462e3a6.gif",
               "title":"SLOT 1-13 MP GENERICO",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/category\/1600#category\/1600",
               "target":"_blank"
            },
            {
               "type":"bp",
               "context":"",
               "slots":1,
               "id":20540,
               "name":"SLOT 1-15 TODAS",
               "image":"http:\/\/bnr.privalia.com\/images\/f8def366727e851cb0ad5f9b733e562f.jpg",
               "title":"SLOT 1-15 TODAS",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/category\/2430#category\/2430",
               "target":""
            },
            {
               "type":"bp",
               "context":"",
               "slots":1,
               "id":20550,
               "name":"SLOT 1-16 TODAS",
               "image":"http:\/\/bnr.privalia.com\/images\/3a6c23af258cc735723bff8c6d5339c8.jpg",
               "title":"SLOT 1-16 TODAS",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/category\/8610#category\/8610",
               "target":""
            },
            {
               "type":"bp",
               "context":"",
               "slots":1,
               "id":20560,
               "name":"SLOT 1-17 TODAS",
               "image":"http:\/\/bnr.privalia.com\/images\/95a5cff2a031ffc526c1c0ee10853d7b.jpg",
               "title":"SLOT 1-17 TODAS",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/category4490#category\/4490",
               "target":""
            },
            {
               "type":"bp",
               "context":"",
               "slots":1,
               "id":20570,
               "name":"SLOT 1-18 TODAS",
               "image":"http:\/\/bnr.privalia.com\/images\/56da21879996829fb4436febb87c80c7.jpg",
               "title":"SLOT 1-18 TODAS",
               "url":"http:\/\/es.privalia.com\/catalog\/shopwindow\/10180#category\/10180",
               "target":""
            }
         ]
      },
      "lastday_block":{
         "title":"\u00daltimo d\u00eda",
         "elements":[
            {
               "type":"cp",
               "slots":1,
               "id":162650,
               "name":"Quiksilver & Roxy Wetsuits",
               "image":"\/front\/get\/photo\/162650_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Quiksilver-&-Roxy-Wetsuits-\/id\/162650\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-03 23:59",
               "endday":"4"
            },
            {
               "type":"cp",
               "slots":1,
               "id":159900,
               "name":"Polar",
               "image":"\/front\/get\/photo\/159900_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Polar-\/id\/159900\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-03 23:59",
               "endday":"4"
            },
            {
               "type":"cp",
               "slots":1,
               "id":171740,
               "name":"Especial Moda: Chaquetas de Piel",
               "image":"\/front\/get\/photo\/171740_-_images_-_960ximg-mosaic-open-slot1.jpg",
               "active":true,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Especial-Moda:-Chaquetas-de-Piel-\/id\/171740\/channel\/1\/classification\/150",
               "inviteandenter":false,
               "channel":1,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "enddate":"2015-09-03 23:59",
               "endday":"4"
            }
         ]
      },
      "next_block":{
         "title":"Pr\u00f3ximamente",
         "elements":[
            {
               "type":"bp",
               "context":"top1",
               "slots":3,
               "id":34830,
               "name":"Premium - Pr\u00f3ximamente Public (web)",
               "image":"http:\/\/bnr.privalia.com\/images\/fbbccab2bf8232e9879aa4fbaca179d4.jpg",
               "title":"Premium - Pr\u00f3ximamente Public (web)",
               "url":"http:\/\/es.privalia.com\/public\/premium",
               "target":""
            },
            {
               "type":"cp",
               "slots":1,
               "id":164070,
               "name":"Jota mas Ge",
               "image":"\/front\/get\/photo\/164070_-_images_-_960ximg-mosaic-next-preopen-slot1.jpg",
               "active":false,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Jota-mas-Ge-\/id\/164070\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-04 07:00:00",
               "startday":"5",
               "enddate":"2015-09-04 06:59",
               "endday":"5",
               "campaign_startdate":"2015-09-04 07:00:00",
               "startdate_pre":"2015-09-03 20:00:00",
               "startday_pre":"4",
               "enddate_pre":"2015-09-04 06:59",
               "endday_pre":"5",
               "campaing_active":false
            },
            {
               "type":"cp",
               "slots":1,
               "id":172500,
               "name":"Sormani Leather Bags",
               "image":"\/front\/get\/photo\/172500_-_images_-_960ximg-mosaic-next-preopen-slot1.jpg",
               "active":false,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Sormani-Leather-Bags-\/id\/172500\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-04 07:00:00",
               "startday":"5",
               "enddate":"2015-09-04 06:59",
               "endday":"5",
               "campaign_startdate":"2015-09-04 07:00:00",
               "startdate_pre":"2015-09-03 20:00:00",
               "startday_pre":"4",
               "enddate_pre":"2015-09-04 06:59",
               "endday_pre":"5",
               "campaing_active":false
            },
            {
               "type":"cp",
               "slots":1,
               "id":172260,
               "name":"Zipz Shoes",
               "image":"\/front\/get\/photo\/172260_-_images_-_960ximg-mosaic-next-preopen-slot1.jpg",
               "active":false,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Zipz-Shoes-\/id\/172260\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-04 07:00:00",
               "startday":"5",
               "enddate":"2015-09-04 06:59",
               "endday":"5",
               "campaign_startdate":"2015-09-04 07:00:00",
               "startdate_pre":"2015-09-03 20:00:00",
               "startday_pre":"4",
               "enddate_pre":"2015-09-04 06:59",
               "endday_pre":"5",
               "campaing_active":false
            },
            {
               "type":"cp",
               "slots":1,
               "id":164460,
               "name":"Institut Karit\u00e9",
               "image":"\/front\/get\/photo\/164460_-_images_-_960ximg-mosaic-next-preopen-slot1.jpg",
               "active":false,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Institut-Karit\u00e9-\/id\/164460\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-04 07:00:00",
               "startday":"5",
               "enddate":"2015-09-04 06:59",
               "endday":"5",
               "campaign_startdate":"2015-09-04 07:00:00",
               "startdate_pre":"2015-09-03 20:00:00",
               "startday_pre":"4",
               "enddate_pre":"2015-09-04 06:59",
               "endday_pre":"5",
               "campaing_active":false
            },
            {
               "type":"cp",
               "slots":1,
               "id":161750,
               "name":"Babynight",
               "image":"\/front\/get\/photo\/161750_-_images_-_960ximg-mosaic-next-preopen-slot1.jpg",
               "active":false,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Babynight-\/id\/161750\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-04 07:00:00",
               "startday":"5",
               "enddate":"2015-09-04 06:59",
               "endday":"5",
               "campaign_startdate":"2015-09-04 07:00:00",
               "startdate_pre":"2015-09-03 20:00:00",
               "startday_pre":"4",
               "enddate_pre":"2015-09-04 06:59",
               "endday_pre":"5",
               "campaing_active":false
            },
            {
               "type":"cp",
               "slots":1,
               "id":164180,
               "name":"Custo Growing",
               "image":"\/front\/get\/photo\/164180_-_images_-_960ximg-mosaic-next-preopen-slot1.jpg",
               "active":false,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Custo-Growing-\/id\/164180\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-04 07:00:00",
               "startday":"5",
               "enddate":"2015-09-04 06:59",
               "endday":"5",
               "campaign_startdate":"2015-09-04 07:00:00",
               "startdate_pre":"2015-09-03 20:00:00",
               "startday_pre":"4",
               "enddate_pre":"2015-09-04 06:59",
               "endday_pre":"5",
               "campaing_active":false
            },
            {
               "type":"cp",
               "slots":1,
               "id":161680,
               "name":"Todo Alfombras",
               "image":"\/front\/get\/photo\/161680_-_images_-_960ximg-mosaic-next-preopen-slot1.jpg",
               "active":false,
               "combinable":true,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Todo-Alfombras-\/id\/161680\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-04 07:00:00",
               "startday":"5",
               "enddate":"2015-09-04 06:59",
               "endday":"5",
               "campaign_startdate":"2015-09-04 07:00:00",
               "startdate_pre":"2015-09-03 20:00:00",
               "startday_pre":"4",
               "enddate_pre":"2015-09-04 06:59",
               "endday_pre":"5",
               "campaing_active":false
            },
            {
               "type":"cp",
               "slots":1,
               "id":172510,
               "name":"Tomasucci",
               "image":"\/front\/get\/photo\/172510_-_images_-_960ximg-mosaic-next-preopen-slot1.jpg",
               "active":false,
               "combinable":false,
               "campprodtype":"GOODS",
               "url":"\/public\/home\/campaign\/Tomasucci-\/id\/172510\/channel\/50\/classification\/150",
               "inviteandenter":false,
               "channel":50,
               "campaign_in_order":false,
               "adult":0,
               "show_adult_modal":false,
               "startdate":"2015-09-04 07:00:00",
               "startday":"5",
               "enddate":"2015-09-04 06:59",
               "endday":"5",
               "campaign_startdate":"2015-09-04 07:00:00",
               "startdate_pre":"2015-09-03 20:00:00",
               "startday_pre":"4",
               "enddate_pre":"2015-09-04 06:59",
               "endday_pre":"5",
               "campaing_active":false
            }
         ]
      }
   },
   "textcodes":[

   ]
}